### ISSUE TITLE
Vendorise dependencies

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-phonegap-cordova#1]
Given this app will run in Phonegap, should we not vendorise the assets such as JQuery / Underscore etc.

**Comment by mattheworiordan** [comment]
@stannedelchev mentioning you here to ensure you receive a notification

**Comment by stannedelchev** [comment]
Agreed. In the future, when the app is more or less finished, I'll move the libraries into a `libs` folder and close the issue.

**Comment by stannedelchev** [comment]
OK, done in 03ccb712551f299e76d50b6f8eb89dc2273ab923 .
