### ISSUE TITLE
iOS Safari does not work

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-phonegap-cordova#4]
Loading up http://ably-phonegap-cordova-demo.herokuapp.com/ in my browser, the app does not work.  I get as far as entering my name

**Comment by stannedelchev** [comment]
I'm unable to use a real device to reproduce this, but in the iOS simulator the application works fine: http://screencast.com/t/VxClRkNriXQT .
This is a visual/styling issue, the screen renders only a part of the app.
Do you have the same issue when running via `cordova run ios` ?

**Comment by mattheworiordan** [comment]
Ok, I can't reproduce now, very odd.  I will close for now and reopen if we have any problems.
