### ISSUE TITLE
History

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-phonegap-cordova#5]
What is the status on the history for the demo?  I don't seem to be getting historical messages when I enter the app

**Comment by stannedelchev** [comment]
The history functionality is completed and is working ok on my end - both on mobile and desktop. 

Please provide me with more details:
- What steps do you do in order to reproduce the issue?
- The device/platform you're using, together with OS/browser version.

**Comment by mattheworiordan** [comment]
@stannedelchev I know what the issue is, history is not being persisted i.e. the channel state is being maintained in memory for around 60s, but then not being persisted to disk.  This is configured with channel rules.  I assume the channel name is always `mobile:chat`?  If so, I have configured a rule now, it should persist hopefully.

**Comment by stannedelchev** [comment]
@mattheworiordan Yes, the channel name is hardcoded as 'mobile:chat'.

```
ABLY_CHANNEL_NAME: 'mobile:chat',
```

I'll test tomorrow and see if I can reproduce the bug by not opening the app for more than 1-2 minutes.

**Comment by mattheworiordan** [comment]
It was an issue on our end, which is now resolved.  All messages were expiring in 86.4s instead of 86,400 seconds!
